### ISSUE TITLE
[Model Catalog Explorer] Leave only related models by category

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#113]
Feedback from Yolanda: Looking at Cycles, the “Compatible Software” tab does not offer useful information (it says that Cycles provides and consumes Cycles variables. Yet the econ model does not show up).  I think if we just put in that tab the related models by category, ie DSSAT, that would be fine.  I looked at PIHM also, and showing that it is related to “Software Script” with configuration "https://w3id.org/okn/i/mint/pihm_flooding” which takes me to RDF Explorer is not very helpful.

**Comment by hvarg** [comment]
For the moment we are only displaying models related by category

**Comment by dgarijo** [comment]
I will close this issue then
