### ISSUE TITLE
Changes for "Files and parameters"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#114]
Feedback from Yolanda: 

- It's confusing to click on files and go to variables tab. Make the file not clickable and add "Look at the Variables tab to see more information about the contents of the inputs and outputs"
- If there are files that are part of the configuration, then we should show the user that those are frozen and mark them somehow, otherwise they will think they have to provide/select/understand those datasets.
- List parameters firs (Call tab Parameters and Files then)

**Comment by hvarg** [comment]
Fixed (1) and (3), any suggestion on what to do for (2) @dgarijo ?

**Comment by dgarijo** [comment]
The same way we say (default) we could say (set by user) or (fixed by user).
