### ISSUE TITLE
[MINT Model catalog explorer] When description is too big, it goes beyond the table

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#133]
**Describe the bug**
When the descriptions of the files are too long, the tables do not appear correctly. 

**To Reproduce**
See: https://dev.mint.isi.edu/south_sudan/models/explore/CYCLES/0.9.4-alpha/cycles-0.9.4-alpha/cycles-0.9.4-alpha-simple-texas and click on variables.

**Comment by hvarg** [comment]
Partially fixed, now the text does not overflow (instead, now scrolls)
Its not the best solution, I need to find a way to make ellipsis into a `wl-expansion`

**Comment by dgarijo** [comment]
You can also show "..."+a tip if the text is too long.

**Comment by hvarg** [comment]
Yes, that is was i'm trying to do, but the component we are using (https://weightless.dev/elements/expansion) does not allow this behavior by default.
I need to figure out a work around.
