### ISSUE TITLE
[Configure Models] Fix description text

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#138]
In, https://dev.mint.isi.edu/south_sudan/models/configure, it says:

------------
Select a model configuration or setup on the left panel.
Welcome to the configure models tool, here you can create or edit new configurations and setups.
------------

it is a circular explanation (eg, configure models is to edit configurations) and we never explain what is a configuration…. Also, this is a page, not a “tool”.

here is some possible text:

------------
This page allows you to create custom configurations of a model, by fixing parameter values or input datasets or by constraining the ranges that parameters can take.

Select a model from the left panel, and edit the parameters and files accordingly.

**Comment by hvarg** [comment]
duplicated of https://github.com/mintproject/mint-ui-lit/issues/140
