### ISSUE TITLE
[Model Explorer] Have to go back 3 pages to return to model catalog

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mint-ui-lit#14]
**Description**
When you click on mode details of a model, then try hitting the web browser back button, it takes 3 clicks to return to the model catalog

**Comment by hvarg** [comment]
I'm aware of this behavior, actually its a bit tricky.
When you go to some model (says `/model_id`) actually this happen:

1. The model is selected and some data is fetched
2. When the data about versions has finished loading, the first version of this model is selected automatically
3. As each version has its own URL, the URL changes to `/model_id/version_id`
4. If this version has configurations, the first one is selected automatically
5. As each configuration has its own URL, the URL changes to `/model_id/version_id/config_id`
4. If this configuration has calibrations, the first one is selected automatically
5. As each calibration has its own URL, the URL changes to `/model_id/version_id/config_id/calibration_id`

Therefore, when you go back this happens:
```
/model_id/version_id/config_id/calibration_id
/model_id/version_id/config_id
/model_id/version_id
/model_id
```

Every change on version, configuration or calibration will generate a change in the URL, adding an extra *back* to the stack.

I can change the *model details* button to go directly to the calibration, but to do this i will need to fetch the data about versions of each model in the search view (or change the API to return this data in `getModels`). But if you go to a model through its URL the problem will still exists.

What do you think @dgarijo?

**Comment by dgarijo** [comment]
I think that this issue should have low priority for now. There is a button for returning to the model catalog, and it is sufficient at the moment to go back without clicking "back" 3 times.

**Comment by hvarg** [comment]
Should work fine now, im closing this issue.
