### ISSUE TITLE
[Model Configuration UI] Add explanation on what configs and setups are

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#140]
In the model configuration and setup page, we don't explain what a model config is, or what a setup is. We should state that a model configuration exposes a particular functionality of a software component, while a setup binds sample input files for its execution.

**Comment by hvarg** [comment]
Its looking like this now:
![Screen Shot 2019-10-31 at 11 05 38](https://user-images.githubusercontent.com/15269912/67902654-8bdf1b00-fbce-11e9-9e87-dd050a971c08.png)
and 
![Screen Shot 2019-10-31 at 11 06 59](https://user-images.githubusercontent.com/15269912/67902673-97324680-fbce-11e9-9062-857d8fdcc6cc.png)

Should I add more text?

**Comment by hvarg** [comment]
Related to https://github.com/mintproject/mint-ui-lit/issues/138

**Comment by dgarijo** [comment]
I am happy with this. Hopefully it will suffice. Thanks!
