### ISSUE TITLE
[Model Catalog Explorer] Show which models are "MINT-Execution ready"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#144]
For each model in the main page (and on each individual page) we should show if that model is "MINT-EXECUTION-READY". This could be a green label such as in the snapshot below.

A model is execution ready if it has a setup (any)
Please @hvarg  contact me to know how do you want me to implement this query

![image](https://user-images.githubusercontent.com/1520666/67706274-b7b39400-f975-11e9-96de-a926e30e4fa9.png)

**Comment by hvarg** [comment]
Added on the main page

**Comment by dgarijo** [comment]
This is addressed. Could you please change the color to green so they get highlighted?

**Comment by hvarg** [comment]
duplicated of https://github.com/mintproject/mint-ui-lit/issues/151
