### ISSUE TITLE
Small changes in overview of models

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#151]
Small changes to the UI overview: Highlight the models that are executable
Add "Not executable in MINT" to the models that don't have setups now.
Move the "versions/configs" to the right

![image](https://user-images.githubusercontent.com/1520666/68052000-eb5c2a00-fca5-11e9-9241-2a1e25f7a427.png)

**Comment by hvarg** [comment]
This should take into consideration the region of the setup?
If a model does not have a setup for the selected region, this part should say "Not executable in MINT"?

**Comment by dgarijo** [comment]
Hmmm, this is a good question.
I would say, since this is a bit more generic, let's not take the region of the setup into account for now. 
however, if it's not too hard, I would have a "Executable in MINT for the selected region" (models with setup in selected region) vs "Not Executable in MINT for the selected region" (models with setups, not in the right region) vs "Not executable in MINT" (no setups)

**Comment by dgarijo** [comment]
Please add the "executable in mint" in green, or highlighted. It's hard to see now
