### ISSUE TITLE
Wrong status of executions

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mint-ui-lit#177]
**Describe the bug**

We have executed the thread https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/W7zUlbzLcxuvwNSU59Vh/3wnCvTO1VmqccXarWw0H/runs

![image](https://user-images.githubusercontent.com/2365990/70275531-2b11a800-1763-11ea-8d77-6edc646eabeb.png)

However, the ensemble says that execution has been successful 

```
Dec 05 12:33:32 node1.mint.isi.edu npm[3922369]: EnaNTF1qst06U4STDl78 ---- update pathway: 3wnCvTO1VmqccXarWw0H
Dec 05 12:33:32 node1.mint.isi.edu npm[3922369]: Finished submitting all executions for model: https://w3id.org/okn/i/mint/hand_v1_simple_ganale
Dec 05 12:33:32 node1.mint.isi.edu npm[3922369]: Finished sending all ensembles for local execution
```

**To Reproduce**
1.  Execute HAND-v1 (https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/W7zUlbzLcxuvwNSU59Vh/3wnCvTO1VmqccXarWw0H/runs)
2. And wait

**Comment by sirspock** [comment]
@varunratnakar The problem persists:

```
➜  ~ curl https://ensemble.mint.isi.edu/v1/logs\?ensemble_id\=7d0d1b058e4576e1e50f8f8bcc3f0383 -o logs.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5197k  100 5197k    0     0  2832k      0  0:00:01  0:00:01 --:--:-- 2830k
➜  ~ ls -lh logs.txt
-rw-r--r--  1 mosorio  staff   5.1M Dec  6 14:49 logs.txt
```
