### ISSUE TITLE
[Model Configuration] Cannot create a setup with one missing input

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#187]
**Describe the bug**
The setup for Topoflow needs to have one fixed input and a variable one (precipitation rates). I was NOT able to create such a setup.

**Comment by hvarg** [comment]
I cant replicate this bug, I was able to create a setup like the one you want:
https://dev.mint.isi.edu/ethiopia/models/configure/TOPOFLOW/topoflow_3.5/topoflow_cfg_simple/e8999759-f9b3-4d0d-8dff-a80b6caa0be5
This is what you want?

**Comment by dgarijo** [comment]
Yes, I will try to regenerate this and will close the issue if I cannot replicate it. Thanks :)

**Comment by dgarijo** [comment]
This issue is no longer valid
