### ISSUE TITLE
[Model Configuration] Parameter assignment method is not filled

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#190]
For some reason, the parameter assignment method is not filled, even though this metadata exists

**Comment by hvarg** [comment]
This is a API problem, for example:
https://api.models.mint.isi.edu/v1.2.0/modelconfigurations/cycles-0.9.4-alpha-advanced-ethiopia-multiple-points?username=mint@isi.edu

Related issue:
https://github.com/mintproject/model-catalog-api/issues/60

**Comment by dgarijo** [comment]
I suspected so, thanks for pinging max
