### ISSUE TITLE
[Model Configuration] Cannot set up default value for setup

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#192]
In some setups, I would like to set the default value but still allow the user for to give a value for that setup. For example, in PIHM, I would like to let the user pick the date but set the default to 2000 instead of 2017.

**Comment by hvarg** [comment]
Fixed on https://github.com/mintproject/mint-ui-lit/commit/93910010a78d7d82657c3fb689b8d439de08881d
