### ISSUE TITLE
If "Datasets" have been pre-loaded, show which ones are selected

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#193]
This is what is shown at the moment:

![image](https://user-images.githubusercontent.com/1520666/70584778-08263000-1b77-11ea-9bd8-f147d8a7e77e.png)

As a user, I only know that some dataset have been pre-selected. I cannot see which are they, and that makes me not trust the model. I should be able to see and review them, if I want. And also, I should have the possibility of editing them

**Comment by dgarijo** [comment]
Same for parameters. It could be hidden and show on demand if there are too many.

**Comment by varunratnakar** [comment]
That information will be visible if they visit the link to the model in the model explorer though right ?

**Comment by dgarijo** [comment]
Yes, but these are the problems I see:

- You cannot do this in "Datasets" or "Setup", you have to go back to the models tab and click on the model title
- You click on the model on the models tab (which doesn't tell you it's the model setup in the model catalog, so it's not intuitive it has that info), then you get sent to another page
- In the model set up you still don't see this information. You have to the "Parameters and file" page.
- In that page you have to scroll to the bottom, and then look at the value names for inputs.

This is very disruptive, even for a user like me who knows where things are at. Instead, if I see the fixed inputs in the "datasets" (with a hidden/show more details) and the fixed parameters (with a hidden/more details) it's informative and non disruptive

**Comment by varunratnakar** [comment]
Ok you've convinced me :)

**Comment by hvarg** [comment]
Fixed

**Comment by varunratnakar** [comment]
Hi everyone,

Sorry about the late reminder !

AGENDA:

Status updates of the timeline as mentioned here:
https://docs.google.com/document/d/1b7WwWcOSKq3OydkW7nHbt6IEA6NPF4HhYYxXFn7HJIM/edit

INPUT DATA:
- Data availability of the raw data in the Corrall System at TACC (Jeaime, Max)
- Registration of Raw Data in the data catalog (Erdong)
- Data preparation for cycles and topoflow (Armen, Max, Scott)

OUTPUT DATA:
- Execution of workflows in Slurm (Max, Jeaime)
- Conversion of output data to standard format: MINT-NetCDF/Datacube (Deborah)
- Automatic Registration of output data (Varun)

Regards,
Varun
