### ISSUE TITLE
[MINT UI] Allow deleting cached code and inputs

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#195]
**Describe the bug**
Related to #179: If I run a model setup in MINT and then I update one of the input files but not the file name or URL, the system will not update my run. There should be a way to tell the system: "redownload inputs". 

The current assumption is that inputs will always work, and this is not the case when testing components. This happens now for some hand runs and topoflow runs.

**Comment by sirspock** [comment]
This is feature is really important for me because I'm investing my time in the manual process.

![image](https://media2.giphy.com/media/I1nwVpCaB4k36/source.gif)

**Comment by varunratnakar** [comment]
I've added a DELETE API for the ensemble manager to delete execution cache (takes the same arguments as the usual POST API to start executions). Check doc here:
It deletes the Cached ensemble document, The cached model zip file and model directory.
Be careful while using it, as it will delete the model directory. So if you have other threads where the same model is running, this might disrupt that
I haven't got anything in the UI to currently invoke this API yet, as I wasn't sure if I should add this "potentially disruptive" capability in the UI (edited)

**Comment by dgarijo** [comment]
Thanks Varun. @sirspock please give it a try and if you are ok with it, close the issue
