### ISSUE TITLE
Error when looking for datasets

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#197]
**Describe the bug**
In this thread: https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/l8uffgtNXqCRexz76puM/datasets; when I go to Datasets and click on edit, I get an infinite waiting gif.
Exceptions that appear in the browser can be seen attached:
![image](https://user-images.githubusercontent.com/1520666/70834339-e7e0b600-1dae-11ea-8d77-e4f58eb9c014.png)

**Comment by hvarg** [comment]
Fixed
