### ISSUE TITLE
[Model configuration] Cannot create new model configurations (more than one)

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#199]
**Describe the bug**
I tried to create 2  setups for PIHM. The first one was created successfully. All subsequent ones did not work. The UI however did NOT show an error message. By reproducing the setup again, I saw this error on the console. It looks like an API error, @sirspock 

![image](https://user-images.githubusercontent.com/1520666/70842713-e24d9500-1ddb-11ea-9bb7-54b0171c53e2.png)

**Comment by dgarijo** [comment]
I would like some tests for this:

- Insert 10 models setups of a model config
- Create at least 2 setups of every model config.

**Comment by sirspock** [comment]
Any update about it?

**Comment by dgarijo** [comment]
Is this a question for me, or for @hvarg? 
I haven't heard anything yet, so I did not try again

**Comment by hvarg** [comment]
Can you test it now, I've fixed several issues on the setup creation, should work now.

**Comment by dgarijo** [comment]
I created some topoflow setups manually, but I will give this a try as soon as I can.
