### ISSUE TITLE
[MINT UI] Results are not processed for visualization

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#201]
**Describe the bug**
After clicking "Save all results" No results are saved for visualization.

**To Reproduce**
Thread ID: https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/pCygfd0EDyH6uZ4WL28h
In "Results" select "save all results". The answer is a 500 error from the server. No error in the UI appears. This is what my console captures:
![image](https://user-images.githubusercontent.com/1520666/70961910-2b018a00-2038-11ea-8b2f-3608f04b8c70.png)

**Comment by varunratnakar** [comment]
@sirspock The server error is:

  File "/usr/src/app/openapi_server/controllers/default_controller.py", line 26, in createmodelthread
    mint_fetch_config)
TypeError: fetch_mint_thread() takes 4 positional arguments but 5 were given

Not sure why 5 arguments are sent to fetch_mint_thread. I see in the code, that only 4 are sent. Could you please take a look if the server needs to be rebuilt ?

**Comment by sirspock** [comment]
Fixed it.
I have added versioning to the Ingestion API. However, I got the commit wrong.
@varunratnakar, are you using node1.ingestion.mint.isi.edu?

**Comment by sirspock** [comment]
Mmmm, two problems in an issue.
@varunratnakar, we are reaching the timeout.
https://github.com/mintproject/ingestion-api/issues/3
