### ISSUE TITLE
[MINT UI] Cannot run model selecting data

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#204]
**Describe the bug**
I select a model (in this case, Topoflow), I select the appropriate data and when I click on "Select", I see the following error:
![image](https://user-images.githubusercontent.com/1520666/71088085-832caf00-2152-11ea-8a3b-f3e07390a5a6.png)

**To Reproduce**
From the UI, go to this thread id: https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/zhprlchxCS092iaddiyD/datasets and on "Datasets" click "Select and Continue".

No errors are shown in the UI

**Comment by hvarg** [comment]
Fixed on https://github.com/hvarg/mint-ui-lit/commit/9471d1cf617728397178f58bc260b7a86c52d95f
