### ISSUE TITLE
[MINT UI] Move some agriculture regions to hydrology regions

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#213]
**Describe the bug**
The regions in https://dev.mint.isi.edu/ethiopia/regions/agriculture are labeled as agriculture. However, they are hydrology regions. 
They should be appropriately credited too:
They come from:  https://www.hydrosheds.org/page/hydrobasins
Citations and acknowledgements of the HydroBASINS data should be made as follows:
Lehner, B., Grill G. (2013): Global river hydrography and network routing: baseline data and new approaches to study the world’s large river systems. Hydrological Processes, 27(15): 2171–2186. Data is available at www.hydrosheds.org.

**Comment by hvarg** [comment]
Fixed! I've copied the agriculture regions into hydrology -> watersheds.

For the moment we are showing the same regions on agriculture.
@dgarijo what map should I show on agriculture?
