### ISSUE TITLE
Extract more metadata from data catalog

### ISSUE THREAD

**Issue by dnfeldman** [mintproject/mint-ui-lit#22]
![image](https://user-images.githubusercontent.com/1411558/63043365-ef379780-be80-11e9-84f2-02e091608cd2.png)

![image](https://user-images.githubusercontent.com/1411558/63043398-02e2fe00-be81-11e9-8b65-a37dffcb2c15.png)

https://github.com/mintproject/mint-ui-lit/blob/1d1f5973f3e4142902c7fb4449708b2038f3d656/src/screens/datasets/actions.ts#L111

1) `"description"` can be extracted from `row["description"]`
2) `"categories"` can be extracted from `dmeta["category_tags"]`

In case new requirements come up, those metadata fields should probably be checked against `dmeta[metadata_name]` and then set to defaults (e.g. `""`) if the value doesn't exist

Lemme know if you have any questions or run into any problems!
Thanks!

**Comment by hvarg** [comment]
Thank you!
This was fixed on https://github.com/mintproject/mint-ui-lit/commit/1bd4c05e0d16b8a2b8d34259dc13320415996f1e I'm closing the issue.
