### ISSUE TITLE
Ability to refresh cache of a component (including inputs)

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#228]
When I submit a run, specifically when testing, I need to change the inputs or component. Now I try to use @sirspock testing environment, but I find that every time I need to refresh, i need to wait for @varunratnakar to delete the components.

It would be great to have a built-in functionality to allow deleting the cached inputs or component from the server. If the inputs were too big, then maybe ask the user, as they would have to be re-downloaded.

**Comment by varunratnakar** [comment]
We already have an API to delete cache for a thread. This deletes:

**Comment by dgarijo** [comment]
I just tried: 
curl -X DELETE -d '{"scenario_id":"NidbAEblXK2ndfl9b57e">, "subgoal_id":"bqirDmqWXD7b4AhOS7Re", "thread_id":"Ro9bYZIAv7i5TRj2drgB"}' https://ensemble.mint.isi.edu/executionsLocal
And got the error:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot DELETE /executionsLocal</pre>
</body>
</html>

**Comment by varunratnakar** [comment]
We need to refresh and restart the ensemble manager. I'll be at my desk in
an hour. Will do it then.

**Comment by dgarijo** [comment]
I tried again. Same error

**Comment by varunratnakar** [comment]
The command should be:

 

curl -X DELETE -H 'Content-type:application/json' -d '{"scenario_id":"NidbAEblXK2ndfl9b57e", "subgoal_id":"bqirDmqWXD7b4AhOS7Re", "thread_id":"Ro9bYZIAv7i5TRj2drB"}' https://ensemble.mint.isi.edu/v1/executionsLocal

**Comment by dgarijo** [comment]
I tested this successfully.
