### ISSUE TITLE
[Model Catalog UI] Special search

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#229]
the MC should allow users to find models based on:

- variable
- region

there should be a search page that allows them to browse based on these.  I know the general search is possible, but this is a very very focused UI that allows users to browse models using the same very small subset of vars that we have in the MINT UI.

**Comment by hvarg** [comment]
Doing this front-end would require me to load all this info on the web-page.
Some queries on the API can ease this feature.
For **interventions** something like this should work:
```SPARQL
WHERE {
  ?model a ?type.
  ?model sd:hasParameter ?param .
  ?param sdm:relevantForIntervention ?interv .
  ?interv a sdm:Intervention .
  ?interv rdfs:label ?intervLabel .
  FILTER REGEX(?intervLabel, 'TEXT_FILTER_HERE')
  VALUES ?type {sdm:ModelConfiguration sdm:ModelConfigurationSetup}
}
```
@sirspock Can we add something like this?
@dgarijo For Driver/Response Variables which attributes should I look into?

**Comment by hvarg** [comment]
For driving variables should be something like:
```SPARQL
WHERE {
  ?model a ?type.
  ?model sdm:usefulForCalculatingIndex ?index .
  ?index rdfs:label ?indexLabel
  FILTER REGEX(?indexLabel, 'TEXT_FILTER_HERE')
  VALUES ?type {sdm:Model sdm:ModelConfiguration sdm:ModelConfigurationSetup}
}
```
