### ISSUE TITLE
[Model Catalog UI] Update to latest release

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#233]
In https://youtu.be/C9rxGT2k9is, @hvarg is showing that it's possible to update the ranges, min and max values associated to parameters.

However, I need to define a setup increasing the the maximum year of FSI and I cannot access to the parameter range edit screen as stated on the video. Would it be possible to deploy that version soon?

**Comment by hvarg** [comment]
Oh, was working for configurations not setups.
I've added "edit configuration defaults" as an option on setup edit.
