### ISSUE TITLE
[MINT-UI] Bug in regions

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#236]
There are still issues with the regions in MINT.

When I select Oromia, only the EACS model shows up but hydro and agro models should show up:

https://dev.mint.isi.edu/ethiopia/regions/administrative

(by the way, note that the URL does not reflect that I have selected Oromia so I could not send the direct link, but I should be able to do that)

Here, when I select Awash, I get many models that are for other basins:

https://dev.mint.isi.edu/ethiopia/regions/hydrology

**Comment by hvarg** [comment]
Fixed on dev, however, we are still displaying models of regions that intercept the bounding box of the selected region.
This is useful to get models for regions smaller that the configured ones. I can change this to only display exact match if you want. @dgarijo what do you think?

I'm closing this issue, I've created [this one](https://github.com/mintproject/mint-ui-lit/issues/242) to track the URL issue.
