### ISSUE TITLE
[Model Catalog UI] Add link to model emulator page

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#239]
If the model is TopoFlow, Cycles, PIHM or HAND, please add a link to the respective emulator page in: https://dev.mint.isi.edu/ethiopia/emulators/topoflow

For now hardcode this information, because it's not available in the API. I have added this to the description at the moment, but having something more explicit would be better.

Once we have this initial version, we can talk about adding this info in a special tab, or something like that.

**Comment by hvarg** [comment]
Working on dev, You can remove the links in the description now.
