### ISSUE TITLE
MINT data catalog issues

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#246]
The Transform button in the regions UI gives a Resource Not Found error:

![image](https://user-images.githubusercontent.com/1520666/73407635-9af96600-42ae-11ea-85ed-a03e41d8c8d2.png)

The data catalog sometimes get stuck for a long time…. We should have a time out and “Retry” button.

![image](https://user-images.githubusercontent.com/1520666/73407642-a056b080-42ae-11ea-9e48-f698db832838.png)

Yolanda Gil

**Comment by hvarg** [comment]
@minhptx can you look into the data-transformation issue? I guess the URL has changed.

https://data-trans.mint.isi.edu/pipeline?slct_adp=10+topoflow4_climate_write_func%252FDcatReadTopoflow4ClimateUploadFunc&clear_add_pipe=&0.inputs.dataset_id=adfca6fb-ad82-4be3-87d8-8f60f9193e43&0.inputs.DEM_bounds=33.37750000071484%2C+7.427499999992511%2C+35.139166666667826%2C+8.439343092637998&0.inputs.DEM_xres_arcsecs=267&0.inputs.DEM_yres_arcsecs=257&0.inputs.var_name=HQprecipitation
