### ISSUE TITLE
[MINT-UI] Explain why the number of runs are necessary

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#251]
When we issue runs, the system tells you that a number of runs will be submitted.
It would be great to have an option to explain these number. Something like:
1000 runs are necessary because you varied parameter X between 1..10 and Y between 1..100

**Comment by sirspock** [comment]
![image](https://user-images.githubusercontent.com/2365990/73786748-c4067480-474e-11ea-97d2-1f6e4ba378d5.png)
