### ISSUE TITLE
[Model Catalog UI] Improve text: You can see this model emulators clicking here.

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#258]
https://dev.mint.isi.edu/ethiopia/models/explore/HAND/HANDv1/hand_v1_simple/hand_v1_simple_ganale
You can see execution results for this model on the emulations page

![image](https://user-images.githubusercontent.com/2365990/73779277-599b0780-4741-11ea-9865-1faa4f3942d2.png)

**Comment by dgarijo** [comment]
Ready to close issue.
