### ISSUE TITLE
[Model Catalog UI] Add a link to docker image

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#259]
Add a link DockerHub image 

https://dev.mint.isi.edu/ethiopia/models/explore/HAND/HANDv1/hand_v1_simple/hand_v1_simple_ganale

![image](https://user-images.githubusercontent.com/2365990/73779618-d4fcb900-4741-11ea-86f6-d86f5b75691b.png)

**Comment by dgarijo** [comment]
I reviewed this issue and it looks good. Ready to close
