### ISSUE TITLE
[Model Catalog UI] [Prepare models] Reorder tabs 

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#261]
https://dev.mint.isi.edu/ethiopia/models/explore/HAND/HANDv1/hand_v1_simple/hand_v1_simple_ganale

Change the order and information displayed on the model view tabs:
- Add assumptions on overview
- Move documentation from Technical info to overview
- Rename compatible software to related models

**Comment by dgarijo** [comment]
Ready to close the issue
