### ISSUE TITLE
[MINT-UI] Add a way of filtering results within a thread

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#276]
Sometimes the threads are too big, and you may want to download only a subset of the results executed. We should be able to filter the desired results (e.g., weed fraction between 0.3 and 0.6)

**Comment by sirspock** [comment]
https://github.com/mintproject/mint-ui-lit/issues/245

**Comment by dgarijo** [comment]
This can be done now by filtering.
