### ISSUE TITLE
Deprecate demo.mint.isi.edu

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#291]
We should add a warning in demo.mint.isi.edu stating that the site is deprecated and that mint.isi.edu is the latest version

**Comment by hvarg** [comment]
![Screen Shot 2020-02-25 at 12 58 12](https://user-images.githubusercontent.com/15269912/75264833-bfbdfc00-57ce-11ea-89e2-41243544cc57.png)
