### ISSUE TITLE
No models are returned in region search

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#292]
No models are returned for any of the regions (hydrology, agriculture, administrative at any level).

See for example:
https://dev.mint.isi.edu/ethiopia/regions/administrative

**Comment by hvarg** [comment]
Fixed for dev (https://github.com/mintproject/mint-ui-lit/commit/f10994b0085dc5eafecc152b9a48e41e5fbbe823), the PR is open in master. @sirspock

**Comment by sirspock** [comment]
Ok

![image](https://user-images.githubusercontent.com/2365990/74867574-c6013380-5309-11ea-90f6-54283961902c.png)
