### ISSUE TITLE
[Model Catalog UI] Specify which version is the latest, and which one is deprecated

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#296]
There is a new property (tag) for model configs and model versions which indicates which is the latest version of a model. The UI should show which one is the latest version and select it by default

**Comment by dgarijo** [comment]
This is super useful for showing the setups in the model catalog

**Comment by hvarg** [comment]
This is working, but for `SoftwareVersion` the client is not returning the tags.
I've open this issue: https://github.com/mintproject/model-catalog-api/issues/94

**Comment by dgarijo** [comment]
All right, if we have it great. If not, we can live without it.
