### ISSUE TITLE
[Model Catalog Explorer] "input variables" should be "input files"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#32]
When you browse the "Configuration Metadata" or "Calibration Metadata" options, you see "Input variables" and "Output variables". However, these headers should be "Input files" and "Output files". They are files, not variables!

**Comment by dgarijo** [comment]
Also, "Adjustable variables" are in reality "Adjustable parameters"

**Comment by hvarg** [comment]
then "Target variables" from (`metadata.targetVariables`) should be "Target parameters" too?

**Comment by dgarijo** [comment]
No, those are target variables for which the model has been calibrated for.
