### ISSUE TITLE
[Model Configuration] Error when entering setups

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#326]
The UI fails when adding a new setup. It looks like it's created partly, because it appears. But then it doesn't load.

**Comment by dgarijo** [comment]
![image](https://user-images.githubusercontent.com/1520666/77108536-9bc19500-69df-11ea-80d8-c6bab4b1493e.png)

**Comment by hvarg** [comment]
I've fixed an error that was happening when you create a new setup with no region selected.
I've checked various ways to configure MODFLOW and that one was the only one that ended on error but the setup loaded fine in my side (no infinite loading).

If the problem persist can you please send me the exact settings you are using?
Also make sure you are running the last version dev version (incognito mode).

**Comment by dgarijo** [comment]
I tested this out and the error is no more.
