### ISSUE TITLE
[Mint Model Catalog Setup UI] Cannot select country regions

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#329]
For some reason, the UI won't allow me selecting Ethiopia when in Ethiopia. What happens if I am doing country-based modeling? Or if I want to select Ethiopia AND South Sudan (which is the case for FSI)?

I should be able to select this.

**Comment by hvarg** [comment]
Fixed on https://github.com/hvarg/mint-ui-lit/commit/6ec07b83311adf7da9fe94c06246a2a24fcb7871
