### ISSUE TITLE
[Model Catalog UI] Long descriptions don't fit well.

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#341]
Look for instance to https://dev.mint.isi.edu/ethiopia/models/explore/CYCLES/cycles_v0.10.2_alpha/cycles-0.10.2-alpha-collection/cycles-0.10.2-alpha-collection-oromia-single-point

The headers of the tables are a single line, and cannot be read well.

**Comment by hvarg** [comment]
Now it shows dots when the text is longer than the header:
![Screen Shot 2020-04-08 at 12 36 38](https://user-images.githubusercontent.com/15269912/78809967-b3b08700-7995-11ea-8af5-22cc83bb73e5.png)

@dgarijo  Do you want to see the description of the Input/Output above the table, something like:
![Screen Shot 2020-04-08 at 12 41 52](https://user-images.githubusercontent.com/15269912/78810454-5f59d700-7996-11ea-9439-5db7486f6392.png)

**Comment by dgarijo** [comment]
Yes, I would like the description above the table as you show in the second picture. What happens if it goes through several lines?

**Comment by hvarg** [comment]
![Screen Shot 2020-04-09 at 11 47 58](https://user-images.githubusercontent.com/15269912/78914186-0fdbdf80-7a58-11ea-9ccc-d41812746e75.png)

**Comment by dgarijo** [comment]
@hvarg maybe instead of the "..." We can have "... (See more)" ? That way users can click and show the full description

**Comment by hvarg** [comment]
It's more difficult to do that as the dots are a CSS feature, to add custom text in the end I need to know the width of the rendered text before rendering it.
It is possible to do it, but will take me a while.

**Comment by dgarijo** [comment]
ok, let's not do it for now then
