### ISSUE TITLE
HAND visualization must point to new viz

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#368]
There is a new visualization for hand
For example:
https://mint.isi.edu/texas/modeling/scenario/2c2Tj7UAz7V2UX7y6zMY/QJdyB7P5hNUfrxzbdkfC/PcqtZYqFJAeXeYCjLfMC/visualize

Must load the hand viz:
https://dev.viz.mint.isi.edu/hand?thread_id=PcqtZYqFJAeXeYCjLfMC&subgoal_id=QJdyB7P5hNUfrxzbdkfC&scenario_id=2c2Tj7UAz7V2UX7y6zMY

Note: I know that this visualization works for the newest modelcofiguration. But, Is the viz compatible with old results?
Maybe, you can ignore this previous note.

**Comment by sirspock** [comment]
@varunratnakar @hvarg This is critical for the friday demo

**Comment by hvarg** [comment]
The visualizations are selected based on the driving and response variables of the models.
For HAND the response variable is `Flooding contour` so I've changed the visualization for that variable, is that correct?
