### ISSUE TITLE
[Model Catalog Ui] When deleting a setup, the link between config and setup is not deleted

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#372]
**Describe the bug**
I created and deleted setups, but the link between config and setup has not been deleted. As a result, it still shows empty:
![image](https://user-images.githubusercontent.com/1520666/79418716-2909f200-7f6a-11ea-9394-928a846dcdaf.png)

I was logged in as texas user.

**Comment by hvarg** [comment]
The API was doing this part, I've noticed that the "deleted" setups also have `rdf:type` so is probably a problem with the API.

**Comment by dgarijo** [comment]
The problem is the link between the config and setup, because that makes it show up in the UI. What you say is also true. In any case, we need to address this problems.

**Comment by sirspock** [comment]
Unable to reproduce

I created a new setup

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/2365990/79493502-6b691880-7fd6-11ea-949d-6971da4b439b.png">

```bash
+ curl -X DELETE http://localhost:8080/v1.4.0/modelconfigurationsetups/212bec9d-eb07-4bf7-aea1-aff869716f17 -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20uemFsYW5kby5jb25uZXhpb24iLCJpYXQiOjE1ODcwNjIxNTYsImV4cCI6MTY0NzA2MjE1Niwic3ViIjoidGV4YXNAaXNpLmVkdSJ9.4cOPzTLrMUKU9pXgB9O-x97uGOk_k7QGcUFj9QpJTuE' -H 'accept: */*' -H 'Content-Type: application/json'
"Deleted"
```

**Comment by dgarijo** [comment]
I have experienced this logged in Texas user. Could that be the issue?

**Comment by sirspock** [comment]
I'm using the Texas user.

**Comment by dgarijo** [comment]
I have added and deleted 2 setups on each user, after editing several times. In both cases, they were deleted successfully. I will close the issue since I cannot reproduce it anymore.
