### ISSUE TITLE
[Model Catalog Explorer] Adjustable variables should be asjudtable parameters

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#43]
I thought this had already been solved. It's adjustable parameters.

**Comment by hvarg** [comment]
ohh! https://github.com/mintproject/mint-ui-lit/commit/9f6d0a36f198b651dda42ffbcaf0e1ca90788156 fixes this issue for the catalog view.
I can see it working here:
https://dev.mint.isi.edu/south_sudan/models/explore/CYCLES/cycles_v0.9.4_alpha/cycles-v2/cycles-v2-advanced-pongo
I found another match on the compare view, its fixed now.
