### ISSUE TITLE
[Model Catalog Explorer] typo in compatible software

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#44]
In Compatible software it shows "configuraion" instead of configuration

**Comment by dgarijo** [comment]
Now compatible software shows "Software Script" Instead, why not showing the label (pihm flooding). And instead of the configuration URL, the description of the script.

**Comment by hvarg** [comment]
Was working that way when the URI of the config was not linked to any model on the model catalog.
However, we are not using this table on compatible software now.
I'm closing this issue for the moment
