### ISSUE TITLE
The first time you click on "Next" after setting up parameters, the page is blank

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#476]
**Describe the bug**
When a thread executes a model for the first time, after hitting "Next" on parameter settings, the page goes blank, and you have to refresh to move on. This is an undesired behavior.

**Comment by hvarg** [comment]
This happens when you edit the model on the first step

**Comment by dgarijo** [comment]
Note that this issue is mostly  fixed. I am happy to keep it open, but the original issue rarely happens now.
