### ISSUE TITLE
[MINT UI] I can change fixed values from setups in run time, and I should not

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#482]
When I am setting up a model, it shows me the fixed values of the files.

However, the fixed values of the parameters show as editable. Some like the type of dataset have been fixed in the setup and should not be editable in runtime.

**Comment by hvarg** [comment]
Adjustable parameters here: ethiopia/models/configure/DSI/dsi_1.0/dsi_1.0_cfg/a504065b-9c16-49c2-b24f-3bd349b158af
 are not compatible with the run parameters (data-type must be non adjustable)
