### ISSUE TITLE
[Model Catalog UI] Incorrect labels used in model details

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#484]
When I look at the drought indices model, the indices show up nicely:

![image](https://user-images.githubusercontent.com/1520666/101235971-dbb9cc80-3681-11eb-9d61-0dd568068d2f.png)

However, when I am browsing the model, I see a typo:

![image](https://user-images.githubusercontent.com/1520666/101235988-102d8880-3682-11eb-9400-4af4387f8aa7.png)

I think the labels should be the same (and hopefully the correct ones)

**Comment by hvarg** [comment]
This is a problem with that particular label: https://dev.mint.isi.edu/ethiopia/models/edit/DSI

**Comment by dgarijo** [comment]
The problem is that in the second screen I think you are showing the URI, not the label (which is fine as shown in the first image)
