### ISSUE TITLE
Changing description of output in configuration changes its position

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#486]
**Describe the bug**
Example: https://dev.mint.isi.edu/ethiopia/models/configure/CYCLES/cycles_v0.10.2_alpha/cycles-0.10.2-alpha-collection

I changed the description of the SOM file, and it moved the output to be in position 10:
![image](https://user-images.githubusercontent.com/1520666/101236345-67812800-3685-11eb-8dce-d896e11a2e91.png)

It was in position 2.
When I tried to use the UI to change back the position, it does not change (does not save)

**Comment by dgarijo** [comment]
I will fix manually the position in the model catalog in the meantime.

**Comment by dgarijo** [comment]
I checked, and it does not remove its previous position, it just adds another:
![image](https://user-images.githubusercontent.com/1520666/101236522-c4c9a900-3686-11eb-9904-adc938f38569.png)

**Comment by hvarg** [comment]
Fixed
