### ISSUE TITLE
Problematic problem statement cannot run any model

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#496]
**Describe the bug**
I created this problem statement: https://dev.mint.isi.edu/ethiopia/modeling/problem_statement/Vmr1gIfr6i9tRwQq8xvG

![image](https://user-images.githubusercontent.com/1520666/101534745-76e5c700-394c-11eb-8fbf-f0478e1f0b45.png)

Now no matted which task I create under that problem, they won't be sent to the ensemble manager. 

@hvarg says that the region id is null, and hence it's not working.

**Comment by varunratnakar** [comment]
The issue was that the problem statement was defined with a smaller end date (2017), and bigger start date (2020). After fixing that in the thread, I can proceed. We should put a check in the editor to make sure it doesn't occur

**Comment by varunratnakar** [comment]
Fixed with 8c5bb44
