### ISSUE TITLE
Create accounts for new users

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#497]
Create 6 accounts for the new mint evaluation.

Users should not use old accounts because they would have access to old threads and tasks.

**Comment by dgarijo** [comment]
We need a total of 6 accounts (could be from 10 - 16)

**Comment by hvarg** [comment]
accounts from eval_user10@isi.edu -> eval_user16@isi.edu

**Comment by hvarg** [comment]
Created accounts from eval_user10@isi.edu to eval_user18@isi.edu
