### ISSUE TITLE
[Model Catalog UI] Title of models sould be clickable

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#500]
In the latest evaluation users said that the model details button is fine, but that clicking on the model name should also take you to the model details page. Right now it's not clickable:

![image](https://user-images.githubusercontent.com/1520666/101955175-312a3800-3bb2-11eb-8e12-c0633a979d11.png)

**Comment by dgarijo** [comment]
@hvarg the title is clickable, but there is no visual hint that would let a user know it is clickable. I suggest underline it on hover; or show it with the same color as "More details"

**Comment by hvarg** [comment]
Fixed on https://github.com/mintproject/mint-ui-lit/commit/217fa4b9df6f7a63da3cd0a56283980cb48c9610
