### ISSUE TITLE
Add a disclaimer

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#514]
We should have a disclaimer in the portal, where it says that the results of the model runs should not be taken out of context, and that some of the models may be uncalibrated for all regions, hence making the results orientative and add a warning if the results are to be used for decision making

**Comment by hvarg** [comment]
Where?

**Comment by dgarijo** [comment]
I would add it on the landing page

**Comment by mosoriob** [comment]
I'm reopening it. Yolanda has mentioned this in an email.

Where?: It should always be at the top of all our demos.

In my opinion, the message must be in the model configuration and modeling section

![image](https://user-images.githubusercontent.com/2365990/153594095-4cfd4c33-a13f-444d-91ee-a06de4eea79b.png)

![image](https://user-images.githubusercontent.com/2365990/153594383-01a31447-3d11-485f-909b-a3909b68db0d.png)

**Comment by hvarg** [comment]
Now looks like this:
![Screen Shot 2022-02-23 at 18 05 12](https://user-images.githubusercontent.com/15269912/155408468-206f6967-be9f-4a2b-bc39-9950ad7fd7d1.png)
