### ISSUE TITLE
New properties for Models

### ISSUE THREAD

**Issue by hvarg** [mintproject/mint-ui-lit#523]
We need to add the following properties at the Model level:

- runtimeEstimation 
- parameterization
- limitations
- theoreticalBasis

@khider those names are ok?

**Comment by khider** [comment]
theoreticalBasis

**Comment by khider** [comment]
Should be theoreticalBasis. Can we also add a "see Also" property that would link to another model in the catalog. Will be needed for coupled models.

**Comment by hvarg** [comment]
@khider Can you write a small description of each attribute

**Comment by khider** [comment]
runtimeEstimation: An estimate of the time required to run example codes or other known configurations
parameterization: Were there any simplifications made to processes to make the model more efficient
limitations: Known restrictions (i.e. cases where the model is known not to be reliable or shouldn't be used)
theoreticalBasis: What is the theory behind the processes described in the model

**Comment by hvarg** [comment]
Thanks @khider !
