### ISSUE TITLE
More categories

### ISSUE THREAD

**Issue by hvarg** [mintproject/mint-ui-lit#527]
In edit mode, we need a few more categories. Well, one with three subcategories:
- Hybrid:
	- Physics-guided empirical models This category would include Physics-guided ML but the empirical model doesn’t have to be of the ML flavor
	- Data assimilation
	- Data + Process driven

Also you can have more than one type: coupled + hybrid and coupled + process-based. So should allow for multiple selections

**Comment by hvarg** [comment]
These are not what we call categories on the model-catalog nor represent changes in the representation of the model so a new property will be needed to add this information, for the moment we can use a name like `modelType`, what do you think @varunratnakar ?

@khider you told me that there's like a spectrum between empirical models and theoretical guided models, can you write down the correct order to display them on the UI?


Have a separate property to annotate this. For the moment use `modelType`.

**Comment by khider** [comment]
Order:
1. Empirical model: models created by observations and experiments 
2. Theory-guided empirical models: empirical models that have been corrected and/or supplemented by theory
3. Data assimilation: Sequential time-stepping procedure in which a process-based model forecast is compared with observations and the model state is adjusted in view of this observations.
4. Theory and empirical models: Models contain both theory-based and empirical components but unlike theory-guided empirical models or data assimilation, one is not used to guide the other. Instead, the components act independently to model different processes.
5. Theory-based model: model that uses theoretical equations to describe their state.
