### ISSUE TITLE
Production webpack doesn't work

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mint-ui-lit#551]
https://user-images.githubusercontent.com/2365990/131558214-cfde13c6-41a7-4bdb-b8e2-bb8dae0579f2.mp4

**Describe the bug**

```bash
Uncaught (in promise) TypeError: this._api[(this._lname + "sGet")] is not a function
    value https://dev.mint.isi.edu/components/2.js:2
    e https://dev.mint.isi.edu/components/2.js:2
    n https://dev.mint.isi.edu/components/3.js?e57bee5c366b5359b7ed:1
    e https://dev.mint.isi.edu/components/2.js:2
    _cached https://dev.mint.isi.edu/components/2.js:2
    n https://dev.mint.isi.edu/components/3.js?e57bee5c366b5359b7ed:1
    e https://dev.mint.isi.edu/components/2.js:2
    i https://dev.mint.isi.edu/components/1.js:22
    value https://dev.mint.isi.edu/components/2.js:2
    value https://dev.mint.isi.edu/components/2.js:2
    n https://dev.mint.isi.edu/components/2.js:2
    value https://dev.mint.isi.edu/components/2.js:2
    value https://dev.mint.isi.edu/components/2.js:2
    value https://dev.mint.isi.edu/components/2.js:2
    n https://dev.mint.isi.edu/components/2.js:2
    _clone https://dev.mint.isi.edu/components/1.js:14
    __commitTemplateResult https://dev.mint.isi.edu/components/1.js:14
    commit https://dev.mint.isi.edu/components/1.js:14
    s https://dev.mint.isi.edu/components/1.js:14
    render https://dev.mint.isi.edu/components/1.js:2
    value https://dev.mint.isi.edu/components/1.js:2
    value https://dev.mint.isi.edu/components/1.js:2
    e https://dev.mint.isi.edu/components/1.js:2
    c https://dev.mint.isi.edu/components/1.js:22
    _invoke https://dev.mint.isi.edu/components/1.js:22
    b https://dev.mint.isi.edu/components/1.js:22
    n https://dev.mint.isi.edu/components/1.js:2
    s https://dev.mint.isi.edu/components/1.js:2


```

**Comment by hvarg** [comment]
Part of the model catalog API is using the name of the constructor to determine the correct function to call for each resource API.

here: https://github.com/mintproject/mint-ui-lit/blob/eb3e325ef69316f247a16f35c471f3a262bf96d7/src/model-catalog-api/default-redux-api.ts#L35

so, part of the production webpack configuration is breaking that...
I need to find a permanent solution, but for the moment, this commit disables the minimization of the js code and avoids the problem:

https://github.com/mintproject/mint-ui-lit/commit/eb3e325ef69316f247a16f35c471f3a262bf96d7

**Comment by mosoriob** [comment]
The workaround works. It will be nice to fix a permanent solution because the `js files` are large now.

**Comment by hvarg** [comment]
I've added a proper solution on https://github.com/mintproject/mint-ui-lit/commit/5d90cfb31cb70df11f2e3bb485e0c014e8709547 however, for some reason I'm getting CORS when doing any POST.

<img width="891" alt="Screen Shot 2021-09-03 at 03 05 49" src="https://user-images.githubusercontent.com/15269912/131964679-4f42e3d6-e6be-4088-a5cb-898ed92b144c.png">

but the requests seems correct to me, @mosoriob can you check if is related?

https://github.com/mintproject/mint-ui-lit/commit/5d90cfb31cb70df11f2e3bb485e0c014e8709547 also enables again `js minimization`

**Comment by mosoriob** [comment]
Fixed by https://github.com/mintproject/installation_public/issues/5
