### ISSUE TITLE
Selecting model setup created from a MIC generated model configuration hangs

### ISSUE THREAD

**Issue by varunratnakar** [mintproject/mint-ui-lit#558]
**Describe the bug**
In a Modeling thread, we get a javascript error when searching for model setups that have been created from a MIC generated model configuration

**To Reproduce**
1. Go to https://dev.mint.isi.edu/ethiopia/modeling/problem_statement/X4vkRI8I3NjGJMUz4cg6/Kb0RhpyExSOW0gXpZ5qZ/bSXqY2LuyLiOYVLLzx8v/models
2. The models progress bar continuously goes on
3. There is a javascript error in the console

**Expected behavior**
The list of models should appear

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: Safari

**Comment by mosoriob** [comment]
I couldn't reproduce it

**Comment by varunratnakar** [comment]
I've noticed this issue. It basically happens whenever a previously uncached model is cached.
