### ISSUE TITLE
Select models can be confusing (at least for me)

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mint-ui-lit#562]
**Is your feature request related to a problem? Please describe.**
The user must click the edit button to search the models. 
It was hard for me.

**Describe the solution you'd like**
Change:
No model selected
No model selected. Click here to select one.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/2365990/160841729-c93b57f9-cdba-4393-babb-30f73b6cc334.png)

**Comment by hvarg** [comment]
Now it has a message and should enable edit on the required inputs as default

**Comment by mosoriob** [comment]
I think a better solution. Click here is a link

 Click here or the edit button to select one

**Comment by hvarg** [comment]
<img width="962" alt="Screen Shot 2022-03-31 at 22 01 41" src="https://user-images.githubusercontent.com/15269912/161174714-31ed00bb-1438-4710-bc3b-921498a6c13e.png">
