### ISSUE TITLE
[Model Catalog Explorer] In Compatible software, replace "Variables" with "Standard Variables"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#68]
Because they are not variables, they are standard names.
Also, can they be made  clickable? Is the URI returned in the query?

**Comment by hvarg** [comment]
I fixed the names, but the URIs are not returned in the query.

**Comment by dgarijo** [comment]
Now they are returned, but we are going to remove this feature at the moment.
