### ISSUE TITLE
Search bar in model catalog not working

### ISSUE THREAD

**Issue by mepearson** [mintproject/mint-ui-lit#7]
The search bar in the model catalog does not appear to be working.  There is no response to either Enter or clicking magnifying glass icon. Windows / Chrome.

**Comment by hvarg** [comment]
Thanks for the report and sorry!
The problem was probably due an error on my improvements into that search bar.
The issue was fixed in [45dbe90](https://github.com/hvarg/mint-ui-lit/commit/45dbe90814f54a577f189570149dc56b5546e1a6), so it will be working on the next release.

**Comment by mepearson** [comment]
Great!

**Comment by hvarg** [comment]
This fix and other improvements to the search bar were added to the [pull request #9](https://github.com/mintproject/mint-ui-lit/pull/9).
