### ISSUE TITLE
[Model Catalog Explorer] Source code from version is missing in the technical details

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#71]
This information is important because it's what points to the particular code of the version. And in some cases different version even have different repositories.

Do you want me to prepare a query for getModelVersionMetadata?

**Comment by dgarijo** [comment]
It would appear before the "Cofig" in the overview, and it would have no I/O and simpler metadata to display (no variables)

**Comment by dgarijo** [comment]
The technical info would be on the "Technical details" tab

**Comment by hvarg** [comment]
Yes, I will need `/getModelVersionMetadata` as its difficult to work with `/getResourceMetadata` and `/getModelConfigurationMetadata` does not work with versions.

**Comment by dgarijo** [comment]
I have added this function; it hasn''t been pushed yet

**Comment by dgarijo** [comment]
Closing: model code and config code are available
