### ISSUE TITLE
[Model Catalog Explorer] Missing metadata from configs and calibs

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#72]
For example, funding source

**Comment by hvarg** [comment]
I've added the `fundS` but its showing nothing because there's no config or setup that has `fundS`.

I've checked using:
```
SELECT *
WHERE {
  GRAPH mcd:mint {
	?x sd:fundingSource ?fundS ;
	   a ?type. 
    VALUES ?type {sdm:ModelConfiguration sdm:ModelConfiguration}
  }
}
```
@dgarijo maybe i'm doing something wrong?

**Comment by dgarijo** [comment]
It's there for models and versions. Not for configs.

**Comment by hvarg** [comment]
It's not working for versions,
```
SELECT *
from <http://ontosoft.isi.edu:3030/modelCatalog-1.1.0/data/mint@isi.edu>  
WHERE {
	?x sd:fundingSource ?fundS ;
	   a ?type. 
    VALUES ?type {sd:SoftwareVersion}
}
```
And its already working for models.

If the problem is with versions, please comment here:  https://github.com/mintproject/mint-ui-lit/issues/41
