### ISSUE TITLE
[Model Catalog Explorer] Bug when selecting the first time a model configuration in the model catalog.

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#98]
How to reproduce:
- Open the model catalog.
- Select a model entry.
- Go back by clicking on "Model catalog" (i.e., not by refreshing the page)
- Select another entry. Now you will not be able to select version/config. Only works if the page is refreshed.

**Comment by hvarg** [comment]
It's working for me, could not find a way to reproduce it.
If you find the bug again please send me a video or more info, I'm closing this issue for the moment.
